version: '3'
volumes:
  pgdata:
services:
  users-api:
    build: ./db
    container_name: users-api
    command: -c 'listen_addresses="*"'
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=users-api_db
    restart: on-failure
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - users-api

networks:
  users-api:
